# Generated by Django 4.0.6 on 2022-08-01 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data i godzina meczu', models.DateTimeField(blank=True)),
                ('Drużyna przeciwna', models.CharField(blank=True, max_length=40)),
                ('Jako gospodarze', models.BooleanField(default=True)),
                ('My', models.PositiveIntegerField(blank=True)),
                ('Przeciwnicy', models.PositiveIntegerField(blank=True)),
                ('Mecz zakończony', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imię', models.CharField(blank=True, max_length=50)),
                ('Nazwisko', models.CharField(blank=True, max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('Numer telefonu', models.PositiveIntegerField()),
                ('Użytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('no', 'Nieobecny'), ('yes', 'Obecny'), ('no_decision', 'Nieodpowiedział'), ('not_sure', 'Niepewny')], default='no_decision', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
        ),
    ]
