# Generated by Django 4.0.6 on 2022-08-02 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data i godzina meczu')),
                ('enemy_team', models.CharField(blank=True, max_length=40, null=True, verbose_name='Drużyna przeciwna')),
                ('at_home', models.BooleanField(default=True, verbose_name='Jako gospodarze')),
                ('our_goals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki nasze')),
                ('enemy_goals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki przeciwników')),
                ('is_end', models.BooleanField(default=False, verbose_name='Mecz zakończony')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='Numer telefonu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('no', 'Nieobecny'), ('yes', 'Obecny'), ('no_decision', 'Nieodpowiedział')], default='no_decision', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
        ),
    ]
