# Generated by Django 4.0.6 on 2022-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='last_modification_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data ostatniej modyfikacji'),
        ),
    ]
