# Generated by Django 4.0.6 on 2022-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='availability',
            field=models.CharField(choices=[('no', 'Nieobecny'), ('yes', 'Obecny'), ('no_decision', 'Nieodpowiedział')], default='no_decision', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='Numer telefonu',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
