# Generated by Django 4.0.6 on 2022-08-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_matchplayer_last_modification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Numer koszulki'),
        ),
    ]
