# Generated by Django 4.0.6 on 2022-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_matchplayer_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Data i godzina meczu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='Drużyna przeciwna',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='My',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='Przeciwnicy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
