# Generated by Django 4.0.6 on 2022-09-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_match_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=160)),
                ('phone_numbers', models.TextField(null=True, verbose_name='Numery adresatów')),
                ('request', models.TextField(null=True, verbose_name='request')),
                ('response', models.TextField(null=True, verbose_name='response')),
                ('players', models.ManyToManyField(to='team.player', verbose_name='Adresaci')),
            ],
        ),
    ]
