# Generated by Django 4.0.6 on 2022-10-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_sms_phone_numbers_alter_sms_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdate',
            name='player',
        ),
        migrations.AlterField(
            model_name='trainingdate',
            name='week_day',
            field=models.CharField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')], max_length=30),
        ),
        migrations.CreateModel(
            name='TrainingDatePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
                ('trainingDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.trainingdate')),
            ],
        ),
    ]
