# Generated by Django 4.0.6 on 2022-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_trainingdate_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdate',
            name='week_day',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek'), (6, 'Sobota'), (7, 'Niedziela')]),
        ),
    ]
