# Generated by Django 4.0.6 on 2022-10-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_trainingdate_week_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdate',
            old_name='week_day',
            new_name='weekday',
        ),
    ]
