# Generated by Django 4.0.6 on 2022-10-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_rename_week_day_trainingdate_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdate',
            name='weekday',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtore', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=20),
        ),
    ]
