# Generated by Django 4.0.6 on 2022-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_trainingdate_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='training_vote',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Głosowanie na treningi - techniczne pole'),
        ),
    ]
